# Generated by Django 4.0.3 on 2022-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='psition',
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default=65987, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
